#!/usr/bin/env python3
"""
Dasa Nala: The Vision Bridge (design_memory_sync.py)
Natively integrates with the `memvid/design-memory` architecture.
Reads the highly semantic markdown files generated by design-memory OCR 
and compiles them into a single, token-compressed TOON block for Dasa Nala.
Prevents "vision blowout" by substituting 40 PNG mockups with pure semantic text.
"""

import os
import sys

def check_design_memory():
    """Verify that the user actually has a populated .design-memory folder."""
    base_path = ".design-memory"
    if not os.path.exists(base_path):
        return False
        
    # It needs to have at least one of the core files
    core_files = ["style.md", "layout.md", "components.md", "reference.md"]
    return any(os.path.exists(os.path.join(base_path, f)) for f in core_files)

def read_and_compress(filepath, max_lines=150):
    """Read a markdown file and truncate if it's insanely long to protect context."""
    if not os.path.exists(filepath):
        return ""
        
    try:
        with open(filepath, "r", encoding='utf-8') as f:
            lines = f.readlines()
            
        if len(lines) > max_lines:
             # Take front matter and trailing summary, drop the middle
             head = "".join(lines[:max_lines//2])
             tail = "".join(lines[-(max_lines//2):])
             return head + "\n\n... [CONTENT COMPRESSED TO SAVE TOKENS] ...\n\n" + tail
        return "".join(lines)
    except Exception as e:
        return f"Error reading {filepath}: {e}"

def main():
    print("🛡️  [Dasa Nala] Analyzing `.design-memory/` Vision Bridge...")
    
    if not check_design_memory():
        print("🟡 [Nala Vision Bridge] No `.design-memory/` output detected. Skipping Vision Bridge.")
        sys.exit(0)
        
    print("⚡ [Nala Vision Bridge] `memvid/design-memory` artifacts detected. Compressing UI semantics...")
    
    # We prioritize the files that actually tell the AI how to build the UI
    files_to_sync = {
        "Global Styles": ".design-memory/style.md",
        "Layout Spec": ".design-memory/layout.md",
        "Component Recipes": ".design-memory/components.md"
    }
    
    bridge_output = "# Vision Bridge: Compiled Design Memory\n\n"
    bridge_output += "> Automatically generated from `memvid/design-memory`. This replaces the need to analyze raw PNGs.\n\n"
    
    for section_name, path in files_to_sync.items():
        if os.path.exists(path):
            content = read_and_compress(path)
            bridge_output += f"## {section_name}\n\n{content}\n\n---\n\n"
            
    # Also grab UI Skills if they exist
    skills_dir = ".design-memory/skills"
    if os.path.isdir(skills_dir):
        bridge_output += "## UI Implementation Skills\n\n"
        for root, _, files in os.walk(skills_dir):
            for file in files:
                if file.endswith(".md"):
                     skill_path = os.path.join(root, file)
                     skill_content = read_and_compress(skill_path, max_lines=50)
                     bridge_output += f"### {file}\n{skill_content}\n\n"
                     
    os.makedirs(".artifacts", exist_ok=True)
    out_path = ".artifacts/vision_bridge.toon"
    
    with open(out_path, "w", encoding='utf-8') as f:
        f.write(bridge_output)
        
    print(f"🟢 [Nala Vision Bridge] Successfully compressed UI Mockups into semantic text.")
    print(f"Context saved to {out_path}.")
    sys.exit(0)

if __name__ == "__main__":
    main()
